# Scalars, Vectors, and Matrices

## Introduction

A *scalar* is a number used to quantify magnitude (e.g. temperature), while a *vector* is used to quantify magnitude and direction (e.g. wind).  

Vectors are typically formatted as a list of numbers with each number corresponding to one direction. Familiar Cartesian coordinates have 2 dimensions, X & Y, and a vector in Cartesian coordinates is 1x2, a one dimensional list with two numbers. 
For example, west-east is the X axis and south-north is the Y axis. The vector (3, 4) indicates wind moving both 3 mph west and 4 mph north, but the combination of these components is a vector of wind moving 5 mph northwest (thanks to the pythagorean theorem, $a^2 + b^2 = c^2$). The *magnitude* is the distance from the origin (0,0), in this case 5. The vector itself is one dimensional and can be depicted as an arrow starting at (0,0) and extending to (3,4) in these Cartesian coordinates.    

***Note:*** A number with magnitude AND two or more directions is called a *tensor*. One way to think of a basic tensor is pinching and pulling a rubber sheet toward you: there is a magnitude of force pulling back toward the initial position (you could use this to launch a pebble like a slingshot) and there is also a magnitude of tension in the rubber sheet itself that will contract back when you let go. Tensors are used to describe gravity in general relativity.   

Vectors are typically formatted as one-dimensional data structures or lists, 1xN, with N as the length of the list.  A *matrix* is a two-dimensional, MxN, data structures. 

Here, we introduce common mathematical notation and the equivalent code implementation in [Numpy](https://numpy.org/).

**Setup:**

In [2]:
%%capture
!pip install numpy

import numpy as np

## Vector & Matrix Operations

### Notation
  
Like scalars, vectors and matrices of numbers can be added and multiplied. However, these operations differ from their scalar counterparts, and are heavily dependent on dimensionality. Matrix and vector dimensions are given as (r x c) where r is the number of rows, and c is the number of columns. Individual vectors are 1 dimensional and notated as a single row (1 x c) or as a single column (r x 1).

For example, $a$ is a [1x3] vector, called a row vector. Vector $b$ is a [3x1] vector, called a column vector. $C$ is a [3x3] matrix. The components of a matrix $C$ are denoted $c_{ij}$, where i is the row index and j is the column index.

***Note:*** Vectors are a special type of matrix. In the following sections, the term "matrices" will be used as a general term to refer to both matrices and vectors.
 
$$
\begin{equation}
\overrightarrow{a} =
\left[
\begin{matrix}
a_{1} & a_{2} & a_{3}
\end{matrix}
\right]
;  \overrightarrow{b} =
\left[
\begin{matrix}
b_{1} \\ b_{2} \\ b_{3}
\end{matrix}
\right]
; C =
\left[
\begin{matrix}
C_{11} & C_{12} & C_{13} \\ C_{21} & C_{22} & C_{23} \\ C_{31} & C_{32} & C_{33}
\end{matrix}
\right]
\end{equation}
$$

**Code:**

In [28]:
# Define vectors and matrices
a = np.array([[1, 2, 3]])        # Row vector (1x3)
b = np.array([[4], [5], [6]])    # Column vector (3x1)
c = np.array([[1, 2, 3],         # Matrix (3x3)
              [4, 5, 6],
              [7, 8, 9]])

# Get the dimensions
dim_a = a.shape
dim_b = b.shape
dim_c = c.shape

print(f'a({dim_a}):\n{a}')
print(f'b({dim_b}):\n{b}')
print(f'c({dim_c}):\n{c}')

a((1, 3)):
[[1 2 3]]
b((3, 1)):
[[4]
 [5]
 [6]]
c((3, 3)):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Transpose
  
When performing operations on vectors, it is easiest to represent a vector as a column vector, and a corresponding row vector as its *transpose*. 
$$
\begin{equation}
\overrightarrow{a}=
\left[
\begin{matrix}
a_{1} \\ a_{2} \\ a_{3}
\end{matrix}
\right]
; \overrightarrow{a}^T=
\left[
\begin{matrix}
a_{1} & a_{2} & a_{3}
\end{matrix}
\right]
\end{equation}
$$

**Code:**

In [13]:
# Define a row vector
a = np.array([[1, 2, 3]])

# Transpose the vector
a_transpose = a.T
print('Transpose of a:\n', a_transpose)
print(f'Dim a: {a.shape}')
print(f'Dim a_transpose: {a_transpose.shape}')

Transpose of a:
 [[1]
 [2]
 [3]]
Dim a: (1, 3)
Dim a_transpose: (3, 1)


### Addition
  
Matrices of the same dimension can be added component-wise, and the result is a new matrix of the same dimension.  

$$
\begin{equation}
\overrightarrow{a} 
+
\overrightarrow{b}
=
\left[
\begin{matrix}
a_{1} \\ a_{2} \\ a_{3}
\end{matrix}
\right]
+
\left[
\begin{matrix}
b_{1} \\ b_{2} \\ b_{3}
\end{matrix}
\right]
=
\left[
\begin{matrix}
a_{1} + b_{1}\\ a_{2} + b_{2} \\ a_{3} + b_{3}
\end{matrix}
\right]
\end{equation}
$$
  
Matrix subtraction works precisely the same way.

**Code:**

In [29]:
# Define two vectors
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

# Calculate the sum of a and b
sum_ab = a + b

# Calculate the difference between b and a
diff_ba = b - a

print('a + b:\n', sum_ab)
print('b - a:\n', diff_ba)

a + b:
 [[5]
 [7]
 [9]]
b - a:
 [[3]
 [3]
 [3]]


### Scalar Multiplication

A matrix can also be multiplied by a scalar by multiplying every component of a matrix by that scalar.

$$
\alpha 
\overrightarrow{a}
=
\begin{equation}
\alpha \left[
\begin{matrix}
a_{1} \\ a_{2} \\ a_{3}
\end{matrix}
\right]
=
\left[
\begin{matrix}
\alpha a_{1} \\ \alpha a_{2} \\ \alpha a_{3}
\end{matrix}
\right]
\end{equation}
$$

**Code:**

In [31]:
# Define a vector and a scalar
alpha = 2
a = np.array([[1], [2], [3]])


product_alpha_a = alpha * a
print('alpha * a:\n', product_alpha_a)

alpha * a:
 [[2]
 [4]
 [6]]


### Dot Product
  
There are other types of vector multiplication. Here, we will introduce one type of vector multiplication: the *dot product*, or *inner product*.  
  
A dot product is the sum of component-wise multiplication of vectors. To perform it, we first multiply each component of the first vector by its corresponding component of the second vector, then we sum the resulting products. The result of a dot product is a scalar.  

$$
\begin{equation}
c =
\sum\limits_{i} a_{i} b_{i}
\end{equation}
$$
    
In vector notation, the dot product can be written as follows  
  
$$
\begin{equation}
\overrightarrow{b} \cdot \overrightarrow{a} = \overrightarrow{b}^T \overrightarrow{a} = 
\left[
\begin{matrix}
b_{1} & b_{2} & b_{3}
\end{matrix}
\right]
\left[
\begin{matrix}
a_{1} \\ a_{2} \\ a_{3}
\end{matrix}
\right]
=a_{1}b_{1} + a_{2}b_{2} + a_{3}b_{3}  
=c
\end{equation}
$$ 
  
Note that the product only works if its “inner dimensions”, the number of columns of $b$ and the number of rows of $a$, are the same.

**Code:**

In [20]:
# Define two vectors
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

dot_product_ba = np.dot(b.T, a)

print('Dot product between b and a:\n', dot_product_ba)

Dot product between a and b:
 [[32]]


### Exercise 1
 
What happens if we try to compute a dot product from vectors whose inner dimensions are different? Write some code in Python that tries to compute the dot product from vectors with different inner dimensions. Report and interpret the error.


In [27]:
# Example for vectors where the inner dimension match
a = np.array([[1, 2, 3]])
b = np.array([[4], [5], [6]])

print(f'dim(a)={a.shape}, dim(b)={b.shape}')

print('Dot product between a and b:\n', np.dot(a, b))

# Define vectors where the inner dimensions don't match
c = # TODO: Your code here
d = # TODO: Your code here

# Calculate the dot product
dot_cd = np.dot(c, d)

dim(a)=(1, 3), dim(b)=(3, 1)
Dot product between a and b:
 [[32]]


ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

### Solution 1

The following solution is just one of many. Make sure to understand why a dot product is not possible when the dimensions don't match.

```python
# Example for vectors where the inner dimension match
a = np.array([[1, 2, 3]])
b = np.array([[4], [5], [6]])

print(f'dim(a)={a.shape}, dim(b)={b.shape}')

print('Dot product between a and b:\n', np.dot(a, b))

# Define vectors where the inner dimensions don't match
c = np.array([[1, 2, 3]])
d = np.array([[4, 5, 6]])

# Calculate the dot product
dot_cd = np.dot(c, d)
```

### Multiplication of Matrix and a Vector Multiplication

The concept of a dot product can be extended to multiplying a matrix with a vector. We can think of this as multiply a single vector $b$ by a set of vectors ${A}$. Rather than doing so individually, we can form the vectors in ${A}$ into a matrix (which we will also call $A$), by storing their transposes in the rows of $A$. Then, we can sequentially compute the dot product of each vector in $A$ with $b$, and store their results in a new vector, $c$. The dimensions of $c$ will depend on how many vectors we stored in $A$.
  
For example, let there be a set of two vectors

$$
\begin{equation}
\overrightarrow{a_{1}}=
\left[
\begin{matrix}
a_{11} \\ a_{21} \\ a_{31}
\end{matrix}
\right]
\end{equation}
$$

and its transpose

$$
\begin{equation}
\overrightarrow{a_{1}}^T=
\left[
\begin{matrix}
a_{11} & a_{12} & a_{13}
\end{matrix}
\right]
\end{equation}
$$

$ \overrightarrow{a_{2}} $ is constructed in the same way to $ \overrightarrow{a_{1}}$ .  
  
Now, let $A$ be

$$
\begin{equation}
A = 
\left[
\begin{matrix}
\overrightarrow{a_{1}}^T \\ \overrightarrow{a_{2}}^T
\end{matrix}
\right]
=
\left[
\begin{matrix}
a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23}
\end{matrix}
\right]
\end{equation} 
$$

Then the product Ab is  

$$
\begin{equation}
A\overrightarrow{b} = 
\left[
\begin{matrix}
a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23}
\end{matrix}
\right]
\left[
\begin{matrix}
b_{1}\\b_{2}\\b_{3}
\end{matrix}
\right]
=
\left[
\begin{matrix}
\overrightarrow{a_{1}} \cdot \overrightarrow{b} \\ \overrightarrow{a_{2}} \cdot \overrightarrow{b}
\end{matrix}
\right]
=
\left[
\begin{matrix}
c_{1} \\ c_{2}
\end{matrix}
\right]
=
\overrightarrow{c}
\end{equation}
$$

**Code:**

In [64]:
# Define a_1 and a_2
a_1 = np.array([[1], [2], [3]])
a_2 = np.array([[4], [5], [6]])

# Define the matrix A
A = np.vstack([a_1.T, a_2.T])

# Define b
b = np.array([[7], [8], [9]])

# Here, we introduce a short form for the dot product (@)
c = A @ b

print('A * b:', c)
print()
print('a_1 * b:', a_1.T @ b)
print('a_2 * b:', a_2.T @ b)

A * b: [[ 50]
 [122]]

a_1 * b: [[50]]
a_2 * b: [[122]]


### Matrix Multiplication 

Matrix multiplication is what we use if we want to multiply a set of vectors ${B}$ by the vectors in $A$, we can perform a similar operation as before. We store the vectors in ${B}$ in the columns of a matrix (also called $B$). Then, we compute the dot product of each vector in the columns of $B$ with each vector in the rows of $A$. We store the results, as we did before, in a new set of column vectors, a matrix $C$. $C$ will have the “outer dimensions” of $A$ and $B$ (the same number of rows as $A$ and the same number of columns as $B$).  
  
For example, let there be two vectors b such that 

$$ 
\overrightarrow{b_{1}} =
\left[
\begin{matrix}
b_{11} \\ b_{21} \\ b_{31}
\end{matrix}
\right] 
$$

and $ \overrightarrow{b_{2}} $ be similar. Then B is given by  

$$
\begin{equation}
B =
\left[
\begin{matrix}
b_{11} & b_{12} \\ b_{21} & b_{22}  \\ b_{31} & b_{32}
\end{matrix}
\right]
\end{equation}
$$

$$
\begin{equation}
AB =
\left[
\begin{matrix}
a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23}
\end{matrix}
\right]
\left[
\begin{matrix}
b_{11} & b_{12} \\ b_{21} & b_{22}  \\ b_{31} & b_{32}
\end{matrix}
\right]
=
\left[
\begin{matrix}
\overrightarrow{a_{1}} \cdot \overrightarrow{b_{1}} & \overrightarrow{a_{1}} \cdot \overrightarrow{b_{2}} \\ \overrightarrow{a_{2}} \cdot \overrightarrow{b_{1}} & \overrightarrow{a_{2}} \cdot \overrightarrow{b_{2}}
\end{matrix}
\right]
=
\left[
\begin{matrix}
c_{11} & c_{12} \\ c_{21} & c_{22}
\end{matrix}
\right]
=
C
\end{equation}
$$
  
The components of $C$ are therefore given by $ c_{ij} = a_{i} \cdot b_{j} $  
  
In this case, the product BA also exists. However, it is very important to understand that matrix multiplication does not commute: $ AB \neq BA.$

**Code**:


In [69]:
# Define Vectors
a_1 = np.array([[1], [2], [3]])
a_2 = np.array([[4], [5], [6]])

b_1 = np.array([[7], [8], [9]])
b_2 = np.array([[10], [11], [12]])

# Define the matrices
A = np.vstack([a_1.T, a_2.T])
B = np.hstack([b_1, b_2])

# Calculate the matrix product
C = A @ B

print('A * B', C)
print()
print('a_1 * b_1', a_1.T @ b_1)
print('a_1 * b_2', a_1.T @ b_2)
print('a_2 * b_1', a_2.T @ b_1)
print('a_2 * b_2', a_2.T @ b_2)

# Calculate the matrix product in reverse order
C_reverse = B @ A

print()
print('B * A', C_reverse)

A * B [[ 50  68]
 [122 167]]

a_1 * b_1 [[50]]
a_1 * b_2 [[68]]
a_2 * b_1 [[122]]
a_2 * b_2 [[167]]

B * A [[47 64 81]
 [52 71 90]
 [57 78 99]]


### Exercise 2

Let D be a 4x2 matrix and E be a 2x7 matrix, what are the dimensions of DE? What are the dimensions of ED?

### Solution 2

- The dimensions of DE are (4, 7)
- ED is not defined since the inner dimensions (7 and 4) don't match
